### ISSUE TITLE
Compiled Version?

### ISSUE THREAD

**Issue by gooddadmike** [jdiamond/todo.txt-ahk#1]
I notice there are two .AHK files. Any issues with compiling this. I would like to use this in my dropbox folder which would sometimes be accessed in systems without AHK installed.

**Comment by jdiamond** [comment]
todo.ahk is the "main" script. Anchor.ahk is included into it. If you have AHK installed, you can right-click todo.ahk and select "Compile Script". I just tested it and it worked fine.

**Comment by gooddadmike** [comment]
Did you test the Anchor Functionality or whatever it does? The reason I
asked is I remember at some point in it's history there was a problem with
the way include files were handled when compiled.
Thanks!
Alion Science and Technology
502-252-3588
mikesearcy.com

**Comment by jdiamond** [comment]
The Anchor functionality makes it so that when you resize the window, the controls get automatically resized with it. It seems to be working fine.

This is my first "large" AHK project so I'm not familiar with it's gotchas, but that one seems to have been resolved.

**Comment by gooddadmike** [comment]
cool

**Comment by jdiamond** [comment]
Just uploaded a zip file containing the exe.
